#!/bin/bash


source common/functions.sh

# start
msg 'My Dotfiles'

OSX=$(test "`uname`" == "Darwin" && echo "x")

if [[ -d "$HOME/Dropbox/github/dotfiles" ]]; then
    msg_checking "Checking dotfiles directory"
else
    msg_install "Cloning" "git@github.com:fabriciofmsilva/dotfiles.git"
    git clone git@github.com:fabriciofmsilva/dotfiles.git $HOME/dotfiles
    msg_ok "OK"
fi

sh brew/global.sh

sh node/global.sh

sh bpkg/global.sh

sh ruby/global.sh

sh sublime/global.sh

sh common/dotfiles.sh

sh vim/global.sh
